### ISSUE TITLE
Venmo Charge isn't working; keyerror: id 

### ISSUE THREAD

**Issue by oooseun** [zackhsi/venmo#53]
Hi, recently, venmo charge hasn't been working. status, reset, etc work fine. uninstalled and reinstalled, still have the same issues. 

See error log below. 

My venmo is opeoo if you want to use it to test. 

Thanks.

➜  work venmo charge @justin-love-2 0.01 "test"
Traceback (most recent call last):
  File "/usr/local/bin/venmo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/venmo/cli.py", line 96, in main
    parse_args()
  File "/usr/local/lib/python2.7/dist-packages/venmo/cli.py", line 91, in parse_args
    func(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/venmo/payment.py", line 20, in charge
    _pay_or_charge(user, amount, note)
  File "/usr/local/lib/python2.7/dist-packages/venmo/payment.py", line 39, in _pay_or_charge
    user_id = venmo.user.id_from_username(username)
  File "/usr/local/lib/python2.7/dist-packages/venmo/user.py", line 12, in id_from_username
    for u in search(username):
  File "/usr/local/lib/python2.7/dist-packages/venmo/user.py", line 34, in search
    'id': u['id'],
KeyError: 'id'

**Comment by zackhsi** [comment]
The issue seems to be related to user ids. The way `charge` currently works is that we search for the username, grab the user id, and charge via user id. That information is no longer available from the Venmo API (`https://api.venmo.com/v1/users`).

Charging by phone number still works as a workaround.

Will update this issue with more information.

Thanks for reporting!

**Comment by zackhsi** [comment]
Fixed in [0.12.0](https://pypi.org/project/venmo/0.12.0/).
