### ISSUE TITLE
Access Token Timing out?

### ISSUE THREAD

**Issue by marshallm94** [zackhsi/venmo#57]
Have you heard of/had any issues yourself of the `access_token` in `~/.venmo/credentials` timing out?

I'm getting the following error:

```
pi@raspberrypi:~/Recurring_Venmo $ venmo charge <user_im_trying_to_charge> 1.00 'test'

Traceback (most recent call last):
  File "/home/pi/.local/bin/venmo", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/venmo/cli.py", line 96, in main
    parse_args()
  File "/home/pi/.local/lib/python3.7/site-packages/venmo/cli.py", line 91, in parse_args
    func(**vars(args))
  File "/home/pi/.local/lib/python3.7/site-packages/venmo/payment.py", line 20, in charge
    _pay_or_charge(user, amount, note)
  File "/home/pi/.local/lib/python3.7/site-packages/venmo/payment.py", line 35, in _pay_or_charge
    user_id = venmo.user.id_from_username(username)
  File "/home/pi/.local/lib/python3.7/site-packages/venmo/user.py", line 12, in id_from_username
    for u in search(username):
  File "/home/pi/.local/lib/python3.7/site-packages/venmo/user.py", line 39, in search
    users = response.json()['data']
KeyError: 'data'
```

However, if I reconfigure from the CL using `venmo configure`, enter password and code that is texted to me, everything works fine with the same command. Any ideas what's happening?

**Comment by zackhsi** [comment]
Yes, the credentials expire. You'll need to refresh periodically.

**Comment by marshallm94** [comment]
Is there anyway around this or is it out of your hands (i.e. in Venmo's hands)? I'm trying to have some requests be run periodically without my needing to interact with the software.

Alternatively, do you know how often one has to reconfigure?

**Comment by zackhsi** [comment]
Not that I'm aware of, sorry.

**Comment by marshallm94** [comment]
Bummer - no worries - great package!
