### ISSUE TITLE
Venmo configure not working

### ISSUE THREAD

**Issue by oooseun** [zackhsi/venmo#58]
Log:
```
venmo configure
Venmo email [None]: email@me.com
Venmo password [None]: *********
Traceback (most recent call last):
  File "/home/oooseun/.local/bin/venmo", line 10, in <module>
    sys.exit(main())
  File "/home/oooseun/.local/lib/python2.7/site-packages/venmo/cli.py", line 96, in main
    parse_args()
  File "/home/oooseun/.local/lib/python2.7/site-packages/venmo/cli.py", line 91, in parse_args
    func(**vars(args))
  File "/home/oooseun/.local/lib/python2.7/site-packages/venmo/auth.py", line 52, in configure
    success = submit_credentials(email, password)
  File "/home/oooseun/.local/lib/python2.7/site-packages/venmo/auth.py", line 229, in submit_credentials
    root = ET.fromstring(filtered_xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 5, column 2
```

**Comment by zackhsi** [comment]
Thanks for reporting. I'm unable to reproduce on my end, sorry. If you have more details, I could try to take a look, but keep in mind Venmo's API has been deprecated for some time.

**Comment by marshallm94** [comment]
I'm able to replicate the above issue - @zackhsi since their API has been deprecated for some time, may I ask if you are using some other service that you have found to work well?

**Comment by zackhsi** [comment]
Sigh, sorry to say I'm not using an alternative.

The code in question is parsing a 2fa form. It's likely they rearranged the form's structure, and the current [extraction logic](https://github.com/zackhsi/venmo/blob/1ce2832ff38d85acbec3de06c5f3f24bb06764e4/venmo/auth.py#L230-L237) no longer works.

**Comment by oooseun** [comment]
That's sad. Venmo still doesn't have an official API?

And thanks Zack! for the effort with put into this project!

**Comment by zackhsi** [comment]
https://techcrunch.com/2016/02/26/how-not-to-run-a-platform/
